### ISSUE TITLE
Sops feature install broken when using 'latest'

### ISSUE THREAD

**Issue by rickardgranberg** [mpriscella/features#10]
It appears the URL to discover the latest has been moved.

`curl https://api.github.com/repos/mozilla/sops/releases/latest` returns:

```
{
  "message": "Moved Permanently",
  "url": "https://api.github.com/repositories/40684033/releases/latest",
  "documentation_url": "https://docs.github.com/v3/#http-redirects"
}
```

**Comment by mpriscella** [comment]
Ah right, I had read that the GitHub org changed for the project. Thanks!
